# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleIGListKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleIGListKit
  pod 'HelperModule', :path => '../IGListKit-Module/HelperModule'

end
